# Generated by Django 3.0.6 on 2020-06-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit1', models.IntegerField(verbose_name='Unidad 1')),
                ('unit2', models.IntegerField(verbose_name='Unidad 2')),
                ('unit3', models.IntegerField(verbose_name='Unidad 3')),
            ],
        ),
        migrations.CreateModel(
            name='Soa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit1', models.IntegerField(verbose_name='Unidad 1')),
                ('unit2', models.IntegerField(verbose_name='Unidad 2')),
                ('unit3', models.IntegerField(verbose_name='Unidad 3')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='apellido')),
                ('arqui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Soa')),
                ('pweb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Programacion_web')),
            ],
        ),
    ]
